function frasedeldia(){
text_array = new Array(
"Si los seres humanos pudieran tan s&oacute;lo entrever los goces infinitos que nos esperan en las zonas que nuestra evoluci&oacute;n animal no ha conquistado todav&iacute;a, lo dejar&iacute;an todo y no cejar&iacute;an hasta que hubieran obtenido esos tesoros &#8211; Sri Aurobindo",
"Un sentimiento adecuado se convierte en la piedra filosofal para cambiar lo normal en y&oacute;guico &#8211; La voz de Babaji",
"Todas tus acciones pueden ser ofrecidas para que sean transformadas en el fuego divino del Yoga &#8211; Kriya Yoga: inspiraciones en el sendero",
"Es a trav&eacute;s de tu vida como llegas a conocer la Verdad de ti mismo. Tu sadhana est&aacute; contenida dentro de las experiencias de tu vida &#8211; Kriya Yoga: inspiraciones en el sendero",
"El Eterno no puede ser conocido a trav&eacute;s del intelecto. No puede ser realizado argumentando o razonando. &eacute;l s&oacute;lo puede ser entendido por la experiencia directa intuitiva &#8211; La voz de Babaji",
"Cuando las personas cumplen su servicio como sacrificio, cualquiera que sea su trabajo o actividad, el universo se eleva y se vuelve sublime &#8211; Bhagavad Gita",
"El trabajo realizado con la actitud mental correcta se vuelve sacrificio. El servicio lo es. La vida se vuelva sagrada gracias a ello &#8211; Bhagavad Gita",
"Nunca te dirijas a nada sino como a una manifestaci&oacute;n de Dios, de otro modo, lanzar&aacute;s un velo de ilusi&oacute;n sobre aquello a lo que mires, y luego ver&aacute;s el mal &#8211; La voz de Babaji",
"Sac&uacute;dete de tus ojos las escamas de la visi&oacute;n imprecisa de lo material, y descubre que todo es divino &#8211; La voz de Babaji",
"Ni m&eacute;rito ni dem&eacute;rito, ni  felicidad ni sufrimiento, Mi forma es la consciencia y el gozo, yo soy Shiva, yo soy Shiva &#8211; Shankaracharya",
"Como practicante de Kriya Yoga incrementa gradualmente el tiempo que dedicas a las pr&aacute;cticas espirituales, porque ellas son un m&eacute;todo seguro que integrar&aacute; la consciencia en  tu vida de todos los d&iacute;as &#8211; Kriya Yoga: inspiraciones en el sendero",
"En cada momento en que estamos presentes hay una oportunidad de progresar &#8211; Kriya Yoga: inspiraciones en el sendero",
"Todo esto que existe es Conocimiento&#8211;Gozo, Pura y Eterna Consciencia Suprema &#8211; La voz de Babaji",
"Al cultivar la presencia viene la consciencia y, cuando viene la consciencia, el gozo viene tambi&eacute;n. En tal estado de ser, consciencia y gozo, todas las acciones pueden ser ejecutadas sin la distorsi&oacute;n del ego &#8211; Kriya Yoga: inspiraciones en el sendero",
"El juego de la consciencia es el &uacute;nico juego en la vida donde t&uacute; siempre ganas. En todos los dem&aacute;s finalmente pierdes, porque s&oacute;lo la Presencia, la Consciencia y el Gozo son eternos e infinitos &#8211; Kriya Yoga: inspiraciones en el sendero",
"No busques m&aacute;s a Dios en parte alguna, sino cont&eacute;mplalo en todas partes &#8211; La voz de Babaji",
"Ning&uacute;n hombre carece de esperanza. Hay un poder infinito en todos. &eacute;l est&aacute; escondido bajo la penumbra circundante de la ignorancia &#8211; La voz de Babaji",
"S&eacute; un h&eacute;roe valiente que con un fuerte esfuerzo corta las enga&ntilde;osas y terribles im&aacute;genes, y su legi&oacute;n de fantas&iacute;as, que surgen al azar y se asoman sin limitaci&oacute;n en la espesura de la mente &#8211; La voz de Babaji",
"Elimina todas las distracciones de tu mente. Logra el ininterrumpido y continuo flujo de esa &uacute;nica consciencia, la estabilidad en el trance que conduce al supremo &eacute;xtasis del gozo &#8211; La voz de Babaji",
"As&iacute; que s&oacute;lo parece haber una salida, y es ir en busca de la propia alma y encontrarla. Est&aacute; ah&iacute;, no intenta esconderse; por el contrario, hace un gran esfuerzo en ayudarte a encontrarla y en hacerse o&iacute;r &#8211; La Madre (Aurobindo Ashram)",
"Cuando quieras saber lo que tu alma conoce, debes hacer un esfuerzo interno, estar muy atento; tras el ruido de la mente y del emocional puedes discernir algo muy sutil, muy tranquilo, muy pac&iacute;fico, que sabe y que dice lo que sabe &#8211; La Madre (Aurobindo Ashram)",
"La relaci&oacute;n que uno tiene con el Supremo nunca tendr&aacute; un igual, nunca ser&aacute; exactamente igual a la de otro. Y esto significa que si uno vive en la Verdad del propio ser, uno es parte indispensable de la creaci&oacute;n &#8211; La Madre (Aurobindo Ashramn)",
"La disciplina y&oacute;guica no trata de anular a la persona, sino de anular al ego, nuestro peque&ntilde;o yo, enfrascado en s&iacute; mismo y en obtener sus peque&ntilde;os y transitorios goces &#8211; www.cristianismoyyoga.com",
"La libertad es la meta de la vida. Las restricciones s&oacute;lo tienen raz&oacute;n de ser para alcanzar un estado de perfecta liberaci&oacute;n &#8211; Swami Ramdas",
"El Ser no ama, es el amor en s&iacute;. No existe, es la existencia en s&iacute;. El alma no conoce, es el conocimiento en s&iacute; &#8211; Swami Vivekananda",
"La recitaci&oacute;n del nombre del Se&ntilde;or, no importa la intenci&oacute;n o motivaci&oacute;n &#8211; sea por amor, escarnio, pereza o maledicencia &#8211; destruir&aacute; los pecados de unos &#8211; Vishnu Purana",
"Haz de cada evento, no importa si mundano o insignificante, una oportunidad para centrarte y practicar auto&#8211;consciencia. Dios no est&aacute; lejos, eres t&uacute; quien est&aacute; ausente, perdido en tus sue&ntilde;os &#8211; Kriya Yoga: inspiraciones en el sendero",
"Un mantra est&aacute; lleno de innumerables potencias divinas. Rep&iacute;telo constantemente, ser&aacute;s dotado de capacidad, fuerza interna espiritual y poder de voluntad &#8211; La voz de Babaji",
"T&uacute; mismo eres el maestro jardinero de tu alma. No te imagines, siquiera por un momento, que alguno de tus pensamientos puede mantenerse sin efectos &#8211; La voz de Babaji",
"T&uacute; simplemente escoges tus pensamientos, y aunque indirectamente, pero de forma segura, modelas tus circunstancias &#8211; La voz de Babaji",
"No permitas que la balsa del pensamiento vaya a la deriva por el oc&eacute;ano de la vida &#8211; La voz de Babaji",
"Eso ha venido s&oacute;lo para probarte, para medir tu fuerza, para probar tu temple. Viene s&oacute;lo para elevarte y disciplinar a tu alma para que est&eacute; tranquila &#8211; La voz de Babaji",
"Si tienes correctamente &eacute;xito con Dios, ninguna destrucci&oacute;n de cualquier clase puede tener significado para ti &#8211; La voz de Babaji",
"Excluye las dudas y los miedos que distraen la l&iacute;nea recta del esfuerzo, volvi&eacute;ndolo torcido, inefectivo e in&uacute;til &#8211; La voz de Babaji",
"La felicidad perfecta viene y todo miedo es conquistado cuando se gana el auto&#8211;conocimiento &#8211; La voz de Babaji",
"El conocimiento intelectual no revelar&aacute; al ser. Debemos aprender el m&eacute;todo de ir m&aacute;s all&aacute; del intelecto y de elevarnos por encima del reino de los pensamientos si queremos realizar el ser absoluto &#8211; La voz de Babaji",
"El miedo es obra de la mente, que es voluble y transitoria, mientras que la intrepidez es la consecuencia de la realizaci&oacute;n de la completa unidad &#8211; La voz de Babaji",
"Recuerda y date cuenta de que los resultados de tus oraciones y tu japa dependen de cu&aacute;n cercano y querido eres para tu Gur&uacute; Deva &#8211; La voz de Babaji",
"El remedio es la gracia, m&aacute;s gracia y todav&iacute;a m&aacute;s gracia del Gur&uacute; &#8211; La voz de Babaji",
"Entr&eacute;gate t&uacute; mismo a la Madre Divina &#8211; La voz de Babaji",
"Te volver&aacute;s uno con la Divinidad en la que meditas &#8211; La voz de Babaji",
"Debes repetir el mantra con pureza, concentraci&oacute;n &uacute;nica de mente y devoci&oacute;n &uacute;nica en la meta &#8211; La voz de Babaji",
"Enciende la l&aacute;mpara del amor (prem) y contempla al Se&ntilde;or Supremo del Amor que reside en cada coraz&oacute;n &#8211; La voz de Babaji",
"Necesitas conocer tu propio ser para conocer el ser de los dem&aacute;s &#8211; La voz de Babaji",
"La persecuci&oacute;n de Dios mediante bhakti, amor espiritual, es el m&aacute;s dulce y el mejor de los empe&ntilde;os humanos &#8211; La voz de Babaji",
"Descubre, mi hijo, m&aacute;s querido que mi propio ser, que hace falta m&aacute;s coraje para sonre&iacute;r y ganar las grandes victorias de la vida &#8211; La voz de Babaji",
"La aniquilaci&oacute;n del peque&ntilde;o ser, la pureza de mente y el amor por todos los seres es la sustancia de la verdadera religi&oacute;n &#8211; La voz de Babaji",
"Medita en Dios en tu coraz&oacute;n. Pronto alcanzar&aacute;s el Gozo eterno &#8211; La voz de Babaji",
"Odiamos un objeto por la ignorancia de nuestra unidad con &eacute;l, y el miedo brota inmediatamente con la dualidad &#8211; La voz de Babaji",
"Cuando nos sentimos como en casa con el mundo entero, manifestando nuestro amor divino interno y s&oacute;lo el amor, reconocemos que surge esa &uacute;nica Realidad sin segundo &#8211; La voz de Babaji",
"No es necesario aniquilar la emoci&oacute;n, sino volcarla hacia el Divino; &eacute;se es el buen camino en el Yoga &#8211; La Madre (Aurobindo Ashram)",
"Un ser humano est&aacute; hecho de muchas partes diferentes, y hace falta tiempo y esfuerzo consciente para armonizar y unificar todas estas partes &#8211; La Madre (Aurobindo Ashram)",
"El Yoga, en su proceso de purificaci&oacute;n, dejar&aacute; al descubierto todos los impulsos y deseos escondidos en ti. Y debes aprender a no esconder las cosas o dejarlas de lado, tienes que afrontarlas y conquistarlas y remodelarlas &#8211; La Madre (Aurobindo Ashram)",
"La fuerza y la luz recibidas por las partes  m&aacute;s elevadas se extienden gradualmente al resto del ser por un proceso de asimilaci&oacute;n, y durante este periodo el progreso de las partes que est&aacute;n al frente es interrumpido &#8211; La Madre (Aurobindo Ashram)",
"S&oacute;lo los a&ntilde;os pasados in&uacute;tilmente te hacen envejecer. Consagra tu vida a la realizaci&oacute;n de algo m&aacute;s elevado y m&aacute;s vasto que t&uacute; mismo y no sentir&aacute;s jam&aacute;s el peso de los a&ntilde;os que pasan &#8211; La Madre (Aurobindo Ashram)",
"La vida es inmortal. Es &uacute;nicamente el cuerpo lo que se disuelve &#8211; La Madre (Aurobindo Ashram)",
"La luz solar es el s&iacute;mbolo de la luz supramental &#8211; La Madre (Aurobindo Ashram)",
"Lo que deber&iacute;ais hacer, es abrir las puertas de vuestro ser de par en par al Divino. A partir del momento en que escond&eacute;is alguna cosa, entr&aacute;is directamente en la mentira &#8211; La Madre (Aurobindo Ashram)",
"Una voluntad perseverante vence la resistencia de todos los obst&aacute;culos &#8211; La Madre (Aurobindo Ashram)",
"Los pensamientos m&aacute;s bellos no nos hacen progresar si no tenemos la voluntad constante de que &eacute;stos se traduzcan en nosotros en sentimientos m&aacute;s elevados, sensaciones m&aacute;s exactas y mejores actos &#8211; La Madre (Aurobindo Ashram)",
"Que tu resoluci&oacute;n sea integral y constante. Entonces, poco a poco, tu futuro te ser&aacute; revelado &#8211; La Madre (Aurobindo Ashram)",
"Los esfuerzos sostenidos aportan siempre grandes resultados &#8211; La Madre (Aurobindo Ashram)",
"El esfuerzo bien dirigido vence la resistencia de todos los obst&aacute;culos &#8211; La Madre (Aurobindo Ashram)",
"Ning&uacute;n esfuerzo es vano. Hay siempre una respuesta, incluso si no la percibimos &#8211; La Madre (Aurobindo Ashram)",
"Cuando el esfuerzo personal es sincero, la ayuda est&aacute; siempre ah&iacute; &#8211; La Madre (Aurobindo Ashram)",
"Todo esfuerzo sincero de progresar y de desembarazarse de los h&aacute;bitos peligrosos recibe una respuesta y es sostenido por una ayuda activa de la Gracia, pero el esfuerzo debe ser sostenido y la aspiraci&oacute;n sincera &#8211; La Madre (Aurobindo Ashram)",
"Persiste en tu aspiraci&oacute;n y tu esfuerzo y tendr&aacute;s &eacute;xito &#8211; La Madre (Aurobindo Ashram)",
"La resistencia es la capacidad de soportar sin estar deprimido &#8211; La Madre (Aurobindo Ashram)",
"Lo m&aacute;s importante es una resistencia regular, tranquila, que no deja que ninguna emotividad, ninguna depresi&oacute;n ponga trabas al progreso. La sinceridad de la aspiraci&oacute;n es la seguridad de la victoria &#8211; La Madre (Aurobindo Ashram)",
"No podemos superar en un d&iacute;a nuestra propia naturaleza. Pero con paciencia y una voluntad persistente la victoria es segura &#8211; La Madre (Aurobindo Ashram)",
"La paciencia es la capacidad de esperar con firmeza la Realizaci&oacute;n que vendr&aacute; &#8211; La Madre (Aurobindo Ashram)",
"Y pase lo que pase si la mente permanece tranquila en todas las circunstancias, la paciencia ser&aacute; m&aacute;s f&aacute;cilmente acrecentada &#8211; La Madre (Aurobindo Ashram)",
"Vamos mucho m&aacute;s r&aacute;pido cuando no tenemos prisa &#8211; La Madre (Aurobindo Ashram)",
"Para realizar es necesario ser paciente. Cuanto m&aacute;s importante y vasta es la realizaci&oacute;n m&aacute;s grande debe ser la paciencia &#8211; La Madre (Aurobindo Ashram)",
"Haz del ideal espiritual el punto central de todos tus pensamientos &#8211; La voz de Babaji",
"Dios no acepta rituales ni dogmas ni teolog&iacute;as, s&oacute;lo acepta corazones &#8211; www.cristianismoyyoga.com",
"El amor unifica. Sin servicio y amor no puedes ni sonar con lograr la realizaci&oacute;n adva&iacute;tica siquiera en millones de vidas &#8211; La voz de Babaji",
"As&iacute; que disuelve la mente y el estado del Gozo Supremo ser&aacute; realizado por toda la eternidad - La voz de Babaji",
"Cultiva la paz mental, llena tu mente con pensamientos puros, y nadie puede ponerse en tu contra - La voz de Babaji", 
"La fe - una fe absoluta - en tu Gur&uacute; es el &uacute;nico e incomparable medio para lograr la meta de la vida y alcanzar lo que est&aacute; m&aacute;s all&aacute; - La voz de Babaji",
"Vu&eacute;lvete hacia la plena luz que brilla m&aacute;s all&aacute; de esta l&aacute;mpara rota de la mente y cesa de vivir centrado en el cuerpo - La voz de Babaji",
"El pensamiento es la fuente de la acci&oacute;n, de la vida y de la manifestaci&oacute;n. As&iacute; que vigila tu pensamiento para perfeccionar tu cuerpo - La voz de Babaji",
"Embellece tu mente para renovar tu cuerpo - La voz de Babaji",
"No cargues con in&uacute;tiles y desventajosos fardos mentales que encorven tu intelecto y que sobrecarguen tu cerebro - La voz de Babaji",
"Sensibiliza a la mente humana ante la suprema y sublime necesidad de una perspectiva espiritual y de una expresi&oacute;n espiritual - La voz de Babaji",
"No paralices tus nervios por el miedo de las imaginaciones err&oacute;neas - La voz de Babaji",
"Ponte en medio de tus pensamientos y contr&oacute;lalos y dir&iacute;gelos hacia buenos fines con orden y paz - La voz de Babaji",
"Deja que una corriente de pensamientos alegres fluyan hacia la meta de la vida y tendr&aacute;s un dulce y suave navegar - La voz de Babaji",
"La mente se vuelve pura cuando todos los deseos y los miedos son aniquilados - La voz de Babaji",
"Lleva una Vida Divina, vive una Vida Divina y enciende la luz de la Vida Divina en todas partes - La voz de Babaji",
"Tu meta debe ser mantener una inmutable disposici&oacute;n de &aacute;nimo, ser puro y gentil, y estar feliz en todas las circunstancias - La voz de Babaji",
"Permanece firme sobre la roca de la verdad a trav&eacute;s del dominio sobre la desquiciada mente - La voz de Babaji",
"No se puede negar o disimular el hecho de que la mente no es sino materia en un estado sutil. Es extremadamente pl&aacute;stica - La voz de Babaji",
"La mente act&uacute;a como un medio de comunicaci&oacute;n entre esp&iacute;ritu y materia. Es justo igual que una escalera que hace que un hombre escale hasta el reino del Gozo Supremo, o que le hace descender hasta el profundo abismo de la ignorancia - La voz de Babaji",
"La mente es un manojo de pensamientos, por supuesto, limitantes y condicionantes - La voz de Babaji",
"Es de la importancia m&aacute;s elevada hacer que la mente se pierda a s&iacute; misma en el infinito, como una burbuja estalla por s&iacute; misma en el oc&eacute;ano de la Realidad - La voz de Babaji",
"La mente debe ser bien manejada e intensamente observada - La voz de Babaji",
"La mente que sigue los pasos de sus propios antojos, fantas&iacute;as y caprichos es atrapada en su propio capullo de deseos - La voz de Babaji",
"Las acciones m&aacute;s comunes de la vida de cada d&iacute;a deben ser minuciosamente observadas, y ganada la experiencia - La voz de Babaji",
"Tenemos que dominar a la mente inferior con la mente superior - La voz de Babaji",
"Conquistar a la mente es conquistar al mundo, ya que la mente y el mundo no son sino el anverso y el reverso de la misma y &uacute;nica cosa - La voz de Babaji",
"Lo que se requiere es una vigilancia constante y persistencia. Si mediante la discriminaci&oacute;n aprendemos la verdad b&aacute;sica de que el Ser y los pensamientos y sentimientos son muy diferentes unos de otros, verdaderamente habremos dado un gran paso hacia la libertad interior - La voz de Babaji",
"La idea de una diferencia fundamental entre nosotros mismos y los pensamientos que surgen en nuestra mente debe ser firmemente entendida - La voz de Babaji",
"La mente debe ser calmada, y por eso todas las sadhanas tienen que realizarse sistem&aacute;ticamente seg&uacute;n la manera y el m&eacute;todo del Kriya - La voz de Babaji",
"El hombre vive de fe. Cuando la fe es dirigida a Dios o al Satgur&uacute; Deva se convierte en la causa de la liberaci&oacute;n del individuo - La voz de Babaji",
"La fe es el factor primordial en el camino del bhakti. No hay bhakti sin fe - La voz de Babaji",
"Si tu mente est&aacute; inquieta no puedes hacer progreso alguno - La voz de Babaji",
"Cuando los rayos de la mente son recogidos mediante la pr&aacute;ctica, la mente llega a concentrarse y obtienes gozo desde el interior - La voz de Babaji",
"Silencia los burbujeantes pensamientos y calma las emociones - La voz de Babaji",
"Debes tener paciencia, una voluntad adamantina y una persistencia incansable - La voz de Babaji",
"Debes ser muy regular en tus pr&aacute;cticas. De otro modo, la pereza y las fuerzas adversas te alejar&aacute;n de la meta - La voz de Babaji",
"Para el progreso espiritual la concentraci&oacute;n debe ser desarrollada en un grado muy elevado - La voz de Babaji",
"Aunque el cuerpo humano es finito, el coraz&oacute;n late a su capacidad infinita, porque el Infinito se revela a S&iacute; mismo en los m&aacute;s interiores recovecos del coraz&oacute;n humano - La voz de Babaji",
"Un amante de Dios tiene que aniquilar su peque&ntilde;o yo completamente hasta que encuentre a Dios en todos los seres - La voz de Babaji",
"Cuando te eleves a la altura del Amor Divino, el&eacute;vate a un grado tal que no veas sino a Dios en tu padre, en tu madre, en todos - La voz de Babaji",
"Cuando veas en tu esposa, no a la esposa, sino al Bienamado, Dios, entonces est&aacute;s en la presencia de Dios, y luego verdaderamente te vuelves Dios - La voz de Babaji",
"Haz que tu amor y tu lealtad por la Verdad, que es Existencia&#8211;Consciencia&#8211;Gozo Absolutos, sean primero encendidos dentro de ti en el fondo de tu coraz&oacute;n - La voz de Babaji",
"Enciende la l&aacute;mpara del amor (prem) y contempla al Se&ntilde;or Supremo del Amor que reside en cada coraz&oacute;n - La voz de Babaji",
"Ninguna barrera de lazos familiares, ninguna consideraci&oacute;n sobre casta o comunidad, ning&uacute;n l&iacute;mite territorial debe obstruir el flujo constante de tu amor universal - La voz de Babaji",
"El amor unifica. Sin servicio y amor no puedes ni so&ntilde;ar con lograr la realizaci&oacute;n adva&iacute;tica (no dualidad) siquiera en millones de vidas - La voz de Babaji",
"El conocimiento es amor difundido, y el amor es conocimiento concentrado - La voz de Babaji",
"El Kriya Yogui dice: estoy sirviendo al Se&ntilde;or en todos los seres. Soy s&oacute;lo un instrumento en las manos del Se&ntilde;or - La voz de Babaji",
"El amor es la naturaleza misma de tu Ser esencial; no act&uacute;es contra esta ley espiritual - La voz de Babaji",
"La gloriosa verdad sobre la Realidad es que ella existe como amor - La voz de Babaji",
"Necesitas conocer tu propio ser para conocer el ser de los dem&aacute;s - La voz de Babaji",
"Dirige todo el amor interior hacia el hombre verdadero, hacia el Ser, tocando el fondo mismo de la vida - La voz de Babaji",
"Nunca te dirijas a nada sino como a una manifestaci&oacute;n de Dios, de otro modo, lanzar&aacute;s un velo de ilusi&oacute;n sobre aquello a lo que mires, y luego ver&aacute;s el mal - La voz de Babaji",
"La consciencia de Dios es la iluminaci&oacute;n que muestra el verdadero ser que se sienta auto-resplandeciente en el alma humana - La voz de Babaji",
"Sac&uacute;dete de tus ojos las escamas de la visi&oacute;n imprecisa de lo material, y descubre que todo es divino - La voz de Babaji",
"La persecuci&oacute;n de Dios mediante bhakti, amor espiritual, es el m&aacute;s dulce y el mejor de los empe&ntilde;os humanos - La voz de Babaji",
"La verdadera sublimaci&oacute;n es el jadeo del coraz&oacute;n humano por el amor por la Divinidad - La voz de Babaji",
"El servicio desinteresado y el amor por Dios son las notas claves de la verdadera religi&oacute;n - La voz de Babaji",
"Ret&iacute;rate en ti mismo y mira adentro - La voz de Babaji",
"El miedo deja traslucir nuestra falta de amor infinito hacia todos los seres, animados e inanimados - La voz de Babaji",
"Odiamos un objeto por la ignorancia de nuestra unidad con &eacute;l, y el miedo brota inmediatamente con la dualidad - La voz de Babaji",
"Cuando nos sentimos como en casa con el mundo entero, manifestando nuestro amor divino interno y s&oacute;lo el amor, reconocemos que surge esa &uacute;nica Realidad sin segundo - La voz de Babaji",
"Si deseas alcanzar la perfecci&oacute;n m&aacute;s elevada debes servir a todas las criaturas con intenso sentimiento, consider&aacute;ndole a &Eacute;l como manifiesto en todas partes - La voz de Babaji",
"Verdaderamente, tu amor hacia el Se&ntilde;or debe engendrar amor por el universo entero, porque t&uacute; debes verlo en todo - La voz de Babaji",
"nciende la Luz del Amor en tu coraz&oacute;n, porque el amor es el camino inmediato al Reino de Dios, el vasto dominio de la paz y la alegr&iacute;a perennes - La voz de Babaji",
"El amor significa la expansi&oacute;n del ser. Es la luz sagrada del alma - La voz de Babaji",
"Dejad que vuestro amor y vuestra lealtad hacia la Verdad, que es Existencia, Conocimiento y Gozo Absolutos, sea encendida primero dentro de vosotros en el fondo de vuestros corazones - La voz de Babaji",
"Todo trabajo, servicio y amor son adoraci&oacute;n para un Kriya yogui. Todos los tipos de trabajo son nobles, elevadores y purificadores - La voz de Babaji",
"El &eacute;nfasis debe ponerse en el desarrollo del car&aacute;cter, con el amor universal y el servicio como base - La voz de Babaji",
"Practica tu sadhana, por un lado, y desarrolla, por el otro, tu relaci&oacute;n con tu Dios y con tu Maestro. En breve, debes aspirar a estar en sinton&iacute;a con el maestro - La voz de Babaji",
"Sigue desarrollando ese elemento de amor por tu Dios y tu Gur&uacute; Deva, y autom&aacute;ticamente te convertir&aacute;s en un hombre y mujer mejor sin siquiera ser consciente de ello - La voz de Babaji",
"Todo bien, toda virtud, toda felicidad y toda paz mental (shanti) resultan del amor - La voz de Babaji",
"El amor o el sentimiento de unidad de todo en el Maestro y en el propio ser, y con ellos, son creadores del orden, la organizaci&oacute;n, la consolidaci&oacute;n, el equilibrio y la tranquilidad - La voz de Babaji",
"Es el amor el que desarrolla un tipo particular de emoci&oacute;n, de car&aacute;cter y de conducta - La voz de Babaji",
"El amor es la ra&iacute;z de todas las virtudes y la lucha sacrificadora por la realizaci&oacute;n de la unidad - La voz de Babaji",
"La sublimaci&oacute;n del amor asegura la salvaci&oacute;n - La voz de Babaji",
"Saboreo Tu radiante amor en mi bebida diaria. T&uacute; eres el oc&eacute;ano de amor y de compasi&oacute;n - La voz de Babaji",
"Permite que nuestro amor por Ti se convierta en una llama rugiente - La voz de Babaji",
"Sin el amor, la vida del hombre est&aacute; vac&iacute;a. Sin el amor, el hombre vive en vano - La voz de Babaji",
"El amor es vital, es omnipresente, un gran poder y la savia de la vida. Da, ama y cultiva este amor mediante el servicio, el japa, el satsanga y la meditaci&oacute;n - La voz de Babaji",
"Dios es amor y el amor es Dios - La voz de Babaji",
"Una voluntad perseverante vence la resistencia de todos los obst&aacute;culos - La Madre (Aurobindo Ashram)",
"Es necesario tener una voluntad invariable de adquirir lo que no tenemos en nuestra naturaleza, de saber lo que no sabemos a&uacute;n, de poder lo que no podemos a&uacute;n - La Madre (Aurobindo Ashram)",
"Es necesario progresar constantemente en la luz y en la paz que provienen de la ausencia de deseo personal - La Madre (Aurobindo Ashram)",
"Cuando tenemos una voluntad firme, no nos queda m&aacute;s remedio que orientarla bien; cuando no tenemos voluntad, es necesario construirse una primero - La Madre (Aurobindo Ashram)",
"Los pensamientos m&aacute;s bellos no nos hacen progresar si no tenemos la voluntad constante de que &eacute;stos se traduzcan en nosotros en sentimientos m&aacute;s elevados, sensaciones m&aacute;s exactas y mejores actos - La Madre (Aurobindo Ashram)",
"Debemos recogernos en una calmada resoluci&oacute;n y en una certeza inquebrantable - La Madre (Aurobindo Ashram)",
"Permanece firme en tu resoluci&oacute;n y todo ir&aacute; bien - La Madre (Aurobindo Ashram)",
"Que tu resoluci&oacute;n sea integral y constante. Entonces, poco a poco, tu futuro te ser&aacute; revelado - La Madre (Aurobindo Ashram)",
"Es dif&iacute;cil desembarazarse de todos los h&aacute;bitos. Es necesario hacerles frente con una firme determinaci&oacute;n - La Madre (Aurobindo Ashram)",
"No hemos de renunciar a una cosa porque sea dif&iacute;cil, por el contrario: cuando m&aacute;s dif&iacute;cil es una cosa, m&aacute;s determinaci&oacute;n hay que tener para lograrla - La Madre (Aurobindo Ashram)",
"S&eacute; firme y paciente: todo ir&aacute; bien - La Madre (Aurobindo Ashram)",
"Los esfuerzos sostenidos aportan siempre grandes resultados - La Madre (Aurobindo Ashram)",
"Siendo regulares en nuestro esfuerzo, tranquilos y firmes en nuestra determinaci&oacute;n, estamos seguros de llegar a la meta - La Madre (Aurobindo Ashram)",
"El esfuerzo bien dirigido vence la resistencia de todos los obst&aacute;culos - La Madre (Aurobindo Ashram)",
"Ning&uacute;n esfuerzo es vano. Hay siempre una respuesta, incluso si no la percibimos - La Madre (Aurobindo Ashram)",
"El esfuerzo personal es indispensable; sin &eacute;ste no puede hacerse nada. Cuando el esfuerzo personal es sincero, la ayuda est&aacute; siempre ah&iacute; - La Madre (Aurobindo Ashram)",
"Todo esfuerzo sincero de progresar y de desembarazarse de los h&aacute;bitos peligrosos recibe una respuesta y es sostenido por una ayuda activa de la Gracia, pero el esfuerzo debe ser sostenido y la aspiraci&oacute;n sincera - La Madre (Aurobindo Ashram)",
"No te inquietes; s&eacute; paciente y perseverante en tu aspiraci&oacute;n - La Madre (Aurobindo Ashram)",
"Persiste en tu aspiraci&oacute;n y se cumplir&aacute; - La Madre (Aurobindo Ashram)",
"Persevera, es la v&iacute;a segura del &eacute;xito. Lo que no has podido realizar en ti el a&ntilde;o anterior, lo har&aacute;s este a&ntilde;o - La Madre (Aurobindo Ashram)",
"Lo que no eres capaz de hacer hoy, lo har&aacute;s ma&ntilde;ana. Persevera y vencer&aacute;s - La Madre (Aurobindo Ashram)",
"Estar sin cesar en contacto con la Verdad no es f&aacute;cil, hace falta tiempo y una gran sinceridad. Pero puedes estar seguro de que te gu&iacute;o y te sostengo con mi fuerza - La Madre (Aurobindo Ashram)",
"&iexcl;Ten valor! Todo ir&aacute; bien si sabemos durar y resistir - La Madre (Aurobindo Ashram)",
"Una resistencia tranquila es el camino m&aacute;s seguro del &eacute;xito - La Madre (Aurobindo Ashram)",
"La victoria es del m&aacute;s resistente - La Madre (Aurobindo Ashram)",
"&Aacute;brete a la Gracia divina y te volver&aacute;s resistente - La Madre (Aurobindo Ashram)",
"Paciencia: indispensable para toda realizaci&oacute;n - La Madre (Aurobindo Ashram)",
"La paciencia es la capacidad de esperar con firmeza la Realizaci&oacute;n que vendr&aacute; - La Madre (Aurobindo Ashram)",
"No podemos superar en un d&iacute;a nuestra propia naturaleza. Pero con paciencia y una voluntad persistente la victoria es segura - La Madre (Aurobindo Ashram)",
"Con paciencia y perseverancia todas las plegarias se ejecutan - La Madre (Aurobindo Ashram)",
"Saber esperar es ganar tiempo - La Madre (Aurobindo Ashram)",
"Y pase lo que pase si la mente permanece tranquila en todas las circunstancias, la paciencia ser&aacute; m&aacute;s f&aacute;cilmente acrecentada - La Madre (Aurobindo Ashram)",
"Vamos mucho m&aacute;s r&aacute;pido cuando no tenemos prisa - La Madre (Aurobindo Ashram)",
"Para quemar etapas hace falta, con una confianza total, sentir que tenemos la eternidad delante de nosotros - La Madre (Aurobindo Ashram)",
"Juzgar es una de las primeras cosas que hay que barrer totalmente de la consciencia antes de poder dar un paso en el camino supramental - La Madre (Aurobindo Ashram)",
"El Divino act&uacute;a en el hombre ignorante, y tambi&eacute;n act&uacute;a en el hombre con conocimiento - La Madre (Aurobindo Ashram)",
"Y ocurre que, aquel que tiene la visi&oacute;n, el que tiene la consciencia, el que es capaz de ver la verdad en todas las cosas, &eacute;ste no tiene absolutamente ninguna necesidad de juzgar nada. - La Madre (Aurobindo Ashram)",
"Una sonrisa expresa la fe de que nada puede resistirse al Divino y de que todo terminar&aacute; bien - La Madre (Aurobindo Ashram)",
"El mundo no mejorar&aacute; m&aacute;s que en la medida en que nosotros nos mejoremos - La Madre (Aurobindo Ashram)",
"Trabajar para el Divino est&aacute; muy bien, y es una alegr&iacute;a. Pero, trabajar con el Divino es una felicidad infinitamente m&aacute;s profunda y m&aacute;s dulce - La Madre (Aurobindo Ashram)",
"La meditaci&oacute;n consiste en que la mente interior observa las cosas para llegar al verdadero conocimiento - La Madre (Aurobindo Ashram)",
"La consciencia superior es una consciencia concentrada, concentrada en la Unidad divina y en la ejecuci&oacute;n de la Voluntad divina - La Madre (Aurobindo Ashram)",
"La meditaci&oacute;n va verdaderamente por buen camino cuando se entra en una consciencia profunda o superior, o cuando esta consciencia desciende a nosotros - La Madre (Aurobindo Ashram)",
"si tienes la idea del Divino en todo, no es m&aacute;s que una idea, una creencia; pero cuando lo sientes y lo ves en todo, es una realizaci&oacute;n - La Madre (Aurobindo Ashram)",
"Debes vigilar, estar alerta y pedir a la Luz de la Madre que te muestre lo que en ti est&aacute; oculto a la mente - La Madre (Aurobindo Ashram)",
"Lo que deber&iacute;ais hacer, es abrir las puertas de vuestro ser de par en par al Divino. A partir del momento en que escond&eacute;is alguna cosa, entr&aacute;is directamente en la mentira - La Madre (Aurobindo Ashram)",
"En lugar de rechazar el movimiento falso, hay que ofrecerlo. Se trata de poner la cosa, el movimiento mismo, proyectarlo en la Luz - La Madre (Aurobindo Ashram)",
"S&oacute;lo los a&ntilde;os pasados in&uacute;tilmente te hacen envejecer. Un a&ntilde;o pasado in&uacute;tilmente es un a&ntilde;o durante el cual no has hecho ning&uacute;n progreso - La Madre (Aurobindo Ashram)",
"Consagra tu vida a la realizaci&oacute;n de algo m&aacute;s elevado y m&aacute;s vasto que t&uacute; mismo y no sentir&aacute;s jam&aacute;s el peso de los a&ntilde;os que pasan - La Madre (Aurobindo Ashram)",
"Si no has renunciado al ego, renunciar al cuerpo no te dar&aacute; la libertad - La Madre (Aurobindo Ashram)",
"La verdadera y total renuncia es renunciar al ego, la que supone un esfuerzo mucho m&aacute;s arduo - La Madre (Aurobindo Ashram)",
"Con el fin de ser capaz de vencer a la muerte y de conquistar la inmortalidad no debemos temer ni desear la muerte - La Madre (Aurobindo Ashram)",
"El Divino est&aacute; en todas partes; y yo repito que para el divino no hay vivos y muertos - La Madre (Aurobindo Ashram)",
"La luz solar es el s&iacute;mbolo de la luz supramental - La Madre (Aurobindo Ashram)"

);

var numero = Math.random();
numero = numero * text_array.length;
numero = numero * .5;
numero = Math.round(numero);

document.write(

"<font color='#000' size='2' face='Arial'>"+text_array[numero]+"</font>")
}